### ISSUE TITLE
Error nachdem ein Schiff sinkt und es Entfernt wird

### ISSUE THREAD

**Issue by 4rr0wx** [4rr0wx/Schiffswert-Spiel#1]
Fehler:
```
Exception in thread "main" java.util.ConcurrentModificationException
      at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
      at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
      at werft.Werft.arbeitetEinenMonat(Werft.java:22)
      at spiel.Main.main(Main.java:19)
```

Fehler beim Schiff aus dem Array löschen.

**Comment by 4rr0wx** [comment]
FIXED
Iterator hinzugefügt um Schiff zu löschen wenn es gesunken ist

**Comment by 4rr0wx** [comment]
FIXED
Iterator hinzugefügt um Schiff zu löschen wenn es gesunken ist
